"""League definitions used by the live matches action."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True, frozen=True)
class LeagueDefinition:
    """Represents a soccer league to collect.

    Attributes:
        slug: ESPN league slug.
        display_name: Human-readable league name.
    """

    slug: str
    display_name: str


LEAGUES: tuple[LeagueDefinition, ...] = (
    LeagueDefinition(slug="fifa.world", display_name="FIFA World Cup"),
    LeagueDefinition(slug="fifa.wwc", display_name="FIFA Women's World Cup"),
    LeagueDefinition(slug="fifa.world.u20", display_name="FIFA Under-20 World Cup"),
    LeagueDefinition(slug="fifa.world.u17", display_name="FIFA Under-17 World Cup"),
    LeagueDefinition(slug="fifa.wworld.u17", display_name="FIFA Under-17 Women's World Cup"),
    LeagueDefinition(slug="fifa.cwc", display_name="FIFA Club World Cup"),
    LeagueDefinition(slug="fifa.friendly", display_name="International Friendly"),
    LeagueDefinition(slug="fifa.friendly.w", display_name="Women's International Friendly"),
    LeagueDefinition(slug="fifa.friendly_u21", display_name="Under-21 International Friendly"),
    LeagueDefinition(slug="fifa.u20.friendly", display_name="International U20 Friendly"),
    LeagueDefinition(slug="fifa.shebelieves", display_name="SheBelieves Cup"),
    LeagueDefinition(slug="fifa.w.champions_cup", display_name="FIFA Women's Champions Cup"),
    LeagueDefinition(slug="fifa.intercontinental_cup", display_name="FIFA Intercontinental Cup"),
    LeagueDefinition(slug="fifa.olympics", display_name="Men's Olympic Soccer Tournament"),
    LeagueDefinition(slug="fifa.w.olympics", display_name="Women's Olympic Soccer Tournament"),
    LeagueDefinition(slug="fifa.worldq", display_name="World Cup Qualifying"),
    LeagueDefinition(slug="fifa.worldq.uefa", display_name="FIFA World Cup Qualifying - UEFA"),
    LeagueDefinition(slug="fifa.worldq.caf", display_name="FIFA World Cup Qualifying - CAF"),
    LeagueDefinition(slug="fifa.worldq.afc", display_name="FIFA World Cup Qualifying - AFC"),
    LeagueDefinition(slug="fifa.worldq.concacaf", display_name="FIFA World Cup Qualifying - Concacaf"),
    LeagueDefinition(slug="fifa.worldq.conmebol", display_name="FIFA World Cup Qualifying - CONMEBOL"),
    LeagueDefinition(slug="fifa.worldq.ofc", display_name="FIFA World Cup Qualifying - OFC"),
    LeagueDefinition(slug="fifa.wwcq.ply", display_name="FIFA Women's World Cup Qualifying - Playoff"),
    LeagueDefinition(slug="fifa.wworldq.uefa", display_name="FIFA Women's World Cup Qualifying - UEFA"),
    LeagueDefinition(slug="uefa.champions", display_name="UEFA Champions League"),
    LeagueDefinition(slug="uefa.champions_qual", display_name="UEFA Champions League Qualifying"),
    LeagueDefinition(slug="uefa.europa", display_name="UEFA Europa League"),
    LeagueDefinition(slug="uefa.europa_qual", display_name="UEFA Europa League Qualifying"),
    LeagueDefinition(slug="uefa.europa.conf", display_name="UEFA Conference League"),
    LeagueDefinition(slug="uefa.europa.conf_qual", display_name="UEFA Conference League Qualifying"),
    LeagueDefinition(slug="uefa.super_cup", display_name="UEFA Super Cup"),
    LeagueDefinition(slug="uefa.wchampions", display_name="UEFA Women's Champions League"),
    LeagueDefinition(slug="uefa.euro", display_name="UEFA European Championship"),
    LeagueDefinition(slug="uefa.euroq", display_name="UEFA European Championship Qualifying"),
    LeagueDefinition(slug="uefa.weuro", display_name="UEFA Women's European Championship"),
    LeagueDefinition(slug="uefa.euro_u21", display_name="UEFA European Under-21 Championship"),
    LeagueDefinition(slug="uefa.euro_u21_qual", display_name="UEFA European Under-21 Championship Qualifying"),
    LeagueDefinition(slug="uefa.euro.u19", display_name="UEFA European Under-19 Championship"),
    LeagueDefinition(slug="uefa.nations", display_name="UEFA Nations League"),
    LeagueDefinition(slug="uefa.w.nations", display_name="UEFA Women's Nations League"),
    LeagueDefinition(slug="eng.1", display_name="English Premier League"),
    LeagueDefinition(slug="eng.2", display_name="English Championship"),
    LeagueDefinition(slug="eng.3", display_name="English League One"),
    LeagueDefinition(slug="eng.4", display_name="English League Two"),
    LeagueDefinition(slug="eng.5", display_name="English National League"),
    LeagueDefinition(slug="eng.fa", display_name="English FA Cup"),
    LeagueDefinition(slug="eng.league_cup", display_name="English Carabao Cup"),
    LeagueDefinition(slug="eng.trophy", display_name="English EFL Trophy"),
    LeagueDefinition(slug="eng.charity", display_name="English FA Community Shield"),
    LeagueDefinition(slug="eng.asia_trophy", display_name="Premier League Asia Trophy"),
    LeagueDefinition(slug="eng.w.1", display_name="English Women's Super League"),
    LeagueDefinition(slug="eng.w.fa", display_name="English Women's FA Cup"),
    LeagueDefinition(slug="eng.w.charity", display_name="English Women's FA Community Shield"),
    LeagueDefinition(slug="esp.1", display_name="Spanish LALIGA"),
    LeagueDefinition(slug="esp.2", display_name="Spanish LALIGA 2"),
    LeagueDefinition(slug="esp.copa_del_rey", display_name="Spanish Copa del Rey"),
    LeagueDefinition(slug="esp.super_cup", display_name="Spanish Supercopa"),
    LeagueDefinition(slug="esp.joan_gamper", display_name="Trofeo Joan Gamper"),
    LeagueDefinition(slug="esp.w.1", display_name="Spanish Liga F"),
    LeagueDefinition(slug="esp.copa_de_la_reina", display_name="Spanish Copa de la Reina"),
    LeagueDefinition(slug="ger.1", display_name="German Bundesliga"),
    LeagueDefinition(slug="ger.2", display_name="German 2. Bundesliga"),
    LeagueDefinition(slug="ger.dfb_pokal", display_name="German Cup"),
    LeagueDefinition(slug="ger.super_cup", display_name="German Supercup"),
    LeagueDefinition(slug="ger.playoff.relegation", display_name="German Bundesliga Promotion/Relegation Playoff"),
    LeagueDefinition(slug="ger.2.promotion.relegation", display_name="German Bundesliga 2 Promotion/Relegation Playoffs"),
    LeagueDefinition(slug="ita.1", display_name="Italian Serie A"),
    LeagueDefinition(slug="ita.2", display_name="Italian Serie B"),
    LeagueDefinition(slug="ita.coppa_italia", display_name="Coppa Italia"),
    LeagueDefinition(slug="ita.super_cup", display_name="Italian Supercoppa"),
    LeagueDefinition(slug="fra.1", display_name="French Ligue 1"),
    LeagueDefinition(slug="fra.2", display_name="French Ligue 2"),
    LeagueDefinition(slug="fra.coupe_de_france", display_name="Coupe de France"),
    LeagueDefinition(slug="fra.super_cup", display_name="French Trophee des Champions"),
    LeagueDefinition(slug="fra.w.1", display_name="French Premiere Ligue"),
    LeagueDefinition(slug="ned.1", display_name="Dutch Eredivisie"),
    LeagueDefinition(slug="ned.2", display_name="Dutch Keuken Kampioen Divisie"),
    LeagueDefinition(slug="ned.3", display_name="Dutch Tweede Divisie"),
    LeagueDefinition(slug="ned.cup", display_name="Dutch KNVB Beker"),
    LeagueDefinition(slug="ned.supercup", display_name="Dutch Johan Cruyff Shield"),
    LeagueDefinition(slug="ned.w.1", display_name="Dutch Vrouwen Eredivisie"),
    LeagueDefinition(slug="ned.w.knvb_cup", display_name="Dutch KNVB Beker Vrouwen"),
    LeagueDefinition(slug="sco.1", display_name="Scottish Premiership"),
    LeagueDefinition(slug="sco.2", display_name="Scottish Championship"),
    LeagueDefinition(slug="sco.3", display_name="Scottish League One"),
    LeagueDefinition(slug="sco.4", display_name="Scottish League Two"),
    LeagueDefinition(slug="sco.tennents", display_name="Scottish Cup"),
    LeagueDefinition(slug="sco.cis", display_name="Scottish League Cup"),
    LeagueDefinition(slug="sco.challenge", display_name="Scottish League Challenge Cup"),
    LeagueDefinition(slug="por.1", display_name="Portuguese Primeira Liga"),
    LeagueDefinition(slug="por.taca.portugal", display_name="Taca de Portugal"),
    LeagueDefinition(slug="bel.1", display_name="Belgian Pro League"),
    LeagueDefinition(slug="aut.1", display_name="Austrian Bundesliga"),
    LeagueDefinition(slug="gre.1", display_name="Greek Super League"),
    LeagueDefinition(slug="tur.1", display_name="Turkish Super Lig"),
    LeagueDefinition(slug="den.1", display_name="Danish Superliga"),
    LeagueDefinition(slug="nor.1", display_name="Norwegian Eliteserien"),
    LeagueDefinition(slug="swe.1", display_name="Swedish Allsvenskan"),
    LeagueDefinition(slug="cyp.1", display_name="Cypriot First Division"),
    LeagueDefinition(slug="irl.1", display_name="Irish Premier Division"),
    LeagueDefinition(slug="rus.1", display_name="Russian Premier League"),
    LeagueDefinition(slug="usa.1", display_name="MLS"),
    LeagueDefinition(slug="usa.open", display_name="U.S. Open Cup"),
    LeagueDefinition(slug="usa.nwsl", display_name="NWSL"),
    LeagueDefinition(slug="usa.nwsl.cup", display_name="NWSL Challenge Cup"),
    LeagueDefinition(slug="usa.nwsl.summer.cup", display_name="NWSL X Liga MX Femenil Summer Cup"),
    LeagueDefinition(slug="usa.usl.1", display_name="USL Championship"),
    LeagueDefinition(slug="usa.usl.l1", display_name="USL League One"),
    LeagueDefinition(slug="usa.w.usl.1", display_name="USL Super League"),
    LeagueDefinition(slug="usa.ncaa.m.1", display_name="NCAA Men's Soccer"),
    LeagueDefinition(slug="usa.ncaa.w.1", display_name="NCAA Women's Soccer"),
    LeagueDefinition(slug="concacaf.champions", display_name="Concacaf Champions Cup"),
    LeagueDefinition(slug="concacaf.leagues.cup", display_name="Leagues Cup"),
    LeagueDefinition(slug="concacaf.gold", display_name="Concacaf Gold Cup"),
    LeagueDefinition(slug="concacaf.nations.league", display_name="Concacaf Nations League"),
    LeagueDefinition(slug="concacaf.w.gold", display_name="Concacaf W Gold Cup"),
    LeagueDefinition(slug="concacaf.w.champions_cup", display_name="Concacaf W Champions Cup"),
    LeagueDefinition(slug="campeones.cup", display_name="Campeones Cup"),
    LeagueDefinition(slug="can.w.nsl", display_name="Northern Super League (Canada)"),
    LeagueDefinition(slug="mex.1", display_name="Mexican Liga BBVA MX"),
    LeagueDefinition(slug="mex.2", display_name="Mexican Liga de Expansion MX"),
    LeagueDefinition(slug="mex.campeon", display_name="Mexican Campeon de Campeones"),
    LeagueDefinition(slug="mex.supercopa", display_name="Mexican Supercopa MX"),
    LeagueDefinition(slug="conmebol.libertadores", display_name="CONMEBOL Libertadores"),
    LeagueDefinition(slug="conmebol.sudamericana", display_name="CONMEBOL Sudamericana"),
    LeagueDefinition(slug="conmebol.recopa", display_name="CONMEBOL Recopa"),
    LeagueDefinition(slug="conmebol.america", display_name="Copa America"),
    LeagueDefinition(slug="conmebol.america_qual", display_name="Copa America Qualifying"),
    LeagueDefinition(slug="conmebol.america.femenina", display_name="Copa America Femenina"),
    LeagueDefinition(slug="global.finalissima", display_name="CONMEBOL-UEFA Cup of Champions"),
    LeagueDefinition(slug="arg.1", display_name="Argentine Liga Profesional de Futbol"),
    LeagueDefinition(slug="arg.copa", display_name="Copa Argentina"),
    LeagueDefinition(slug="bra.1", display_name="Brazilian Serie A"),
    LeagueDefinition(slug="bra.2", display_name="Brazilian Serie B"),
    LeagueDefinition(slug="bra.copa_do_brazil", display_name="Copa do Brasil"),
    LeagueDefinition(slug="chi.1", display_name="Chilean Primera Division"),
    LeagueDefinition(slug="col.1", display_name="Colombian Primera A"),
    LeagueDefinition(slug="par.1", display_name="Paraguayan Primera Division"),
    LeagueDefinition(slug="per.1", display_name="Peruvian Liga 1"),
    LeagueDefinition(slug="uru.1", display_name="Liga AUF Uruguaya"),
    LeagueDefinition(slug="bol.1", display_name="Bolivian Liga Profesional"),
    LeagueDefinition(slug="ecu.1", display_name="LigaPro Ecuador"),
    LeagueDefinition(slug="ven.1", display_name="Venezuelan Primera Division"),
    LeagueDefinition(slug="caf.nations", display_name="Africa Cup of Nations"),
    LeagueDefinition(slug="caf.nations_qual", display_name="Africa Cup of Nations Qualifying"),
    LeagueDefinition(slug="caf.champions", display_name="CAF Champions League"),
    LeagueDefinition(slug="caf.confed", display_name="CAF Confederation Cup"),
    LeagueDefinition(slug="rsa.1", display_name="South African Premiership"),
    LeagueDefinition(slug="nga.1", display_name="Nigerian Professional League"),
    LeagueDefinition(slug="gha.1", display_name="Ghanaian Premier League"),
    LeagueDefinition(slug="afc.champions", display_name="AFC Champions League Elite"),
    LeagueDefinition(slug="afc.cup", display_name="AFC Champions League Two"),
    LeagueDefinition(slug="afc.asian.cup", display_name="AFC Asian Cup"),
    LeagueDefinition(slug="ksa.1", display_name="Saudi Pro League"),
    LeagueDefinition(slug="ksa.kings.cup", display_name="Saudi King's Cup"),
    LeagueDefinition(slug="jpn.1", display_name="Japanese J.League"),
    LeagueDefinition(slug="chn.1", display_name="Chinese Super League"),
    LeagueDefinition(slug="ind.1", display_name="Indian Super League"),
    LeagueDefinition(slug="tha.1", display_name="Thai League 1"),
    LeagueDefinition(slug="mys.1", display_name="Malaysian Super League"),
    LeagueDefinition(slug="idn.1", display_name="Indonesian Super League"),
    LeagueDefinition(slug="sgp.1", display_name="Singaporean Premier League"),
    LeagueDefinition(slug="aus.1", display_name="Australian A-League Men"),
    LeagueDefinition(slug="aus.w.1", display_name="Australian A-League Women"),
    LeagueDefinition(slug="club.friendly", display_name="Club Friendly"),
    LeagueDefinition(slug="nonfifa", display_name="Non-FIFA Friendly"),
    LeagueDefinition(slug="friendly.emirates_cup", display_name="Emirates Cup"),
    LeagueDefinition(slug="global.champs_cup", display_name="International Champions Cup"),
    LeagueDefinition(slug="generic.ussf", display_name="Misc. U.S. Soccer Games"),
)
